@baseUrl = http://localhost:3000/api/
@establishmentId = 1
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

# @name login
POST {{baseUrl}}/log/in
content-type: application/x-www-form-urlencoded

username=JeanBonnot&password=%26Test123

### establishment ###
# Read All establishment
GET {{baseUrl}}/establishment/
Authorization: Bearer {{accessToken}}
###
# Read One establishment
GET {{baseUrl}}/establishment/{{establishmentId}}/
Authorization: Bearer {{accessToken}}
###
# Create establishment
POST {{baseUrl}}/establishment/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "La tanière du Castor"
}
###
# Update establishment
PUT {{baseUrl}}/establishment/{{establishmentId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Ti'Chou"
}
###
# Delete establishment
DELETE  {{baseUrl}}/establishment/{{establishmentId}}/
Authorization: Bearer {{accessToken}}
