@baseUrl = http://localhost:3000/api/
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}
@sequenceId = 5
@userId = 4

# @name login
POST {{baseUrl}}/log/in
content-type: application/x-www-form-urlencoded

username=JeanBonnot&password=%26Test123

### Sequence ###
# Read All sequences
GET {{baseUrl}}/user/{{userId}}/sequence/
Authorization: Bearer {{accessToken}}

###
# Read One sequence
GET {{baseUrl}}/user/{{userId}}/sequence/{{sequenceId}}/
Authorization: Bearer {{accessToken}}

###
# Create sequence
POST {{baseUrl}}/user/{{userId}}/sequence/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Tartiflette",
  "user_id": {{userId}}
}
###
# Update sequence
PUT {{baseUrl}}/user/{{userId}}/sequence/{{sequenceId}}/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Faire de la bière"
}
###
# Delete sequence
DELETE  {{baseUrl}}/user/{{userId}}/sequence/{{sequenceId}}/
Authorization: Bearer {{accessToken}}
