@baseUrl = http://localhost:3000/api/
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}
@userId = 5
@sessionId = 2

# @name login
POST {{baseUrl}}/log/in
content-type: application/x-www-form-urlencoded

username=JeanBonnot&password=%26Test123

### Session ###
# Read Session
GET {{baseUrl}}/user/{{userId}}/session/{{sessionId}}
Authorization: Bearer {{accessToken}}

###
# Create Session
POST {{baseUrl}}/user/{{userId}}/session
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Faire de la bolo",
  "sequence_id": 8,
  "card_id": 6,
  "tool_id": 19,
  "comments": "Par groupe de 4 max, mélanger les niveaux",
  "time": 60,
  "is_face_to_face": true,
  "is_group_work": true,
  "equipment": "Laptop"
}
###
# Update Session
PUT {{baseUrl}}/user/{{userId}}/session/{{sessionId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Tvuyruc",
  "activity_id": 6,
  "comments": "Par groupe de 4 max, mélanger les niveaux",
  "time": 60,
  "is_face_to_face": true,
  "is_group_work": true,
  "equipment": "Laptop"
}
###
# Delete Session
DELETE {{baseUrl}}/user/{{userId}}/session/{{sessionId}}
Authorization: Bearer {{accessToken}}
