@baseUrl = http://localhost:3000/api/user/
@userId = 5

@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

# @name login
POST http://localhost:3000/api/log/in
content-type: application/x-www-form-urlencoded

username=JeanBonnot&password=%26Test123

### Session ###
# Read All users
GET {{baseUrl}}/
Authorization: Bearer {{accessToken}}
###
# Read One user
GET {{baseUrl}}/{{userId}}/
Authorization: Bearer {{accessToken}}
###
# Create User
POST {{baseUrl}}/
Content-Type: application/json

{
  "username": "JeanBonnot",
  "email": "jb@truc.fr",
  "password": "&Test123",
  "establishment_id": 2
}
###
# Update User
PUT {{baseUrl}}/{{userId}}
Content-Type: application/json

{
  "password": "&Test1111"
}
###
# Delete Tool
DELETE  {{baseUrl}}/{{userId}}/
