@baseUrl = http://localhost:3000/api/user/
@sequenceId = 1
@userId = 1

### Sequence ###
# Read All sequences
GET {{baseUrl}}/{{userId}}/sequence/
###
# Read One sequence
GET {{baseUrl}}/{{userId}}/sequence/{{sequenceId}}/
###
# Create sequence
POST {{baseUrl}}/{{userId}}/sequence/
Content-Type: application/json

{
  "name": "Faire de la frênette"
}
###
# Update sequence
PUT {{baseUrl}}/{{userId}}/sequence/{{sequenceId}}/
Content-Type: application/json

{
  "name": "Faire de la bière"
}
###
# Delete sequence
DELETE  {{baseUrl}}/{{userId}}/sequence/{{sequenceId}}/
